name: book_tracker
description: "A Flutter book tracking app using Riverpod state management."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # --- Required packages for the project ---
  flutter_riverpod: ^2.4.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # --- App assets (add later when needed) ---
  # assets:
  #  - assets/covers/
   # - assets/icons/
    #- assets/mock/

  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
